package agekey

import "testing"

// These two are real, checksum-valid Bech32 strings (generated by an
// independent encoder against 32 bytes of fixed data, not by this
// package), one with the plain X25519 hrp and one with a plugin-style
// nested hrp — the two shapes ValidateRecipient has to accept.
const (
	validX25519Recipient = "age1qqqsyqcyq5rqwzqfpg9scrgwpugpzysnzs23v9ccrydpk8qarc0savhh7m"
	validPluginRecipient = "age1yubikey1qqqsyqcyq5rqwzqfpg9scrgwpugpzysnzs23v9ccrydpk8qarc0s9hkmc0"
)

func TestValidateRecipientAccepts(t *testing.T) {
	for _, s := range []string{validX25519Recipient, validPluginRecipient} {
		if err := ValidateRecipient(s); err != nil {
			t.Errorf("ValidateRecipient(%q) = %v, want nil", s, err)
		}
	}
}

func TestValidateRecipientRejectsBadChecksum(t *testing.T) {
	// Flip the last character, which is part of the checksum.
	mutated := validX25519Recipient[:len(validX25519Recipient)-1] + "x"
	if mutated == validX25519Recipient {
		t.Fatal("mutation produced the same string")
	}
	if err := ValidateRecipient(mutated); err == nil {
		t.Errorf("ValidateRecipient(%q) = nil, want an error (bad checksum)", mutated)
	}
}

func TestValidateRecipientRejectsMalformed(t *testing.T) {
	cases := []string{
		"",
		"not-an-age-key",
		"age1",                    // no data/checksum at all
		"age1bad checksum here!!", // invalid characters
		"AGE1QQQSYQCYQ5RQWZQFPG9SCRGWPUGPZYSNZS23V9CCRYDPK8QARC0SAVHh7m",     // mixed case
		"ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBogus",                         // wrong format entirely
		"bitcoin1qqqsyqcyq5rqwzqfpg9scrgwpugpzysnzs23v9ccrydpk8qarc0savhh7m", // hrp doesn't start with "age"
	}
	for _, s := range cases {
		if err := ValidateRecipient(s); err == nil {
			t.Errorf("ValidateRecipient(%q) = nil, want an error", s)
		}
	}
}
