package agekey

import (
	"strings"
	"testing"
)

// These two are real, checksum-valid Bech32 strings (generated by an
// independent encoder against 32 bytes of fixed data, not by this
// package), one with the plain X25519 hrp and one with a plugin-style
// nested hrp — the two shapes ValidateRecipient has to accept.
const (
	validX25519Recipient = "age1qqqsyqcyq5rqwzqfpg9scrgwpugpzysnzs23v9ccrydpk8qarc0savhh7m"
	validPluginRecipient = "age1yubikey1qqqsyqcyq5rqwzqfpg9scrgwpugpzysnzs23v9ccrydpk8qarc0s9hkmc0"
)

func TestValidateRecipientAccepts(t *testing.T) {
	for _, s := range []string{validX25519Recipient, validPluginRecipient} {
		if err := ValidateRecipient(s); err != nil {
			t.Errorf("ValidateRecipient(%q) = %v, want nil", s, err)
		}
	}
}

func TestValidateRecipientRejectsBadChecksum(t *testing.T) {
	// Flip the last character, which is part of the checksum.
	mutated := validX25519Recipient[:len(validX25519Recipient)-1] + "x"
	if mutated == validX25519Recipient {
		t.Fatal("mutation produced the same string")
	}
	if err := ValidateRecipient(mutated); err == nil {
		t.Errorf("ValidateRecipient(%q) = nil, want an error (bad checksum)", mutated)
	}
}

func TestValidateRecipientRejectsMalformed(t *testing.T) {
	cases := []string{
		"",
		"not-an-age-key",
		"age1",                    // no data/checksum at all
		"age1bad checksum here!!", // invalid characters
		"AGE1QQQSYQCYQ5RQWZQFPG9SCRGWPUGPZYSNZS23V9CCRYDPK8QARC0SAVHh7m",     // mixed case
		"ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBogus",                         // wrong format entirely
		"bitcoin1qqqsyqcyq5rqwzqfpg9scrgwpugpzysnzs23v9ccrydpk8qarc0savhh7m", // hrp doesn't start with "age"
	}
	for _, s := range cases {
		if err := ValidateRecipient(s); err == nil {
			t.Errorf("ValidateRecipient(%q) = nil, want an error", s)
		}
	}
}

// TestValidateRecipientRejectsNonPrintableHRP is the one malformed-shape
// message TestValidateRecipientRejectsMalformed doesn't reach: a
// human-readable part that starts with "age" (so it clears that check)
// but contains a character outside isPrintableASCII's range — a space,
// here, which has no case and so also clears the earlier
// all-lower-or-all-upper check.
func TestValidateRecipientRejectsNonPrintableHRP(t *testing.T) {
	s := "age 1qqqqqqqqqq" // hrp "age ", a literal space before the separator
	err := ValidateRecipient(s)
	if err == nil {
		t.Fatalf("ValidateRecipient(%q) = nil, want an error", s)
	}
	if got := err.Error(); !strings.Contains(got, "non-printable") {
		t.Errorf("error = %q, want it to mention non-printable characters", got)
	}
}

// TestIsPrintableASCIIBoundaries pins isPrintableASCII's range directly:
// 32 (space) and 127 (DEL) are excluded, 33 ('!') and 126 ('~') are the
// first and last characters it accepts.
func TestIsPrintableASCIIBoundaries(t *testing.T) {
	cases := []struct {
		r    rune
		want bool
	}{
		{32, false},
		{33, true},
		{126, true},
		{127, false},
	}
	for _, c := range cases {
		if got := isPrintableASCII(string(c.r)); got != c.want {
			t.Errorf("isPrintableASCII(%q) = %v, want %v", string(c.r), got, c.want)
		}
	}
}
